name: openvino-sample-consumer
base: core24
summary: Sample OpenVINO content consumer for testing and validation
description: |
  This snap is used for validating the openvino-toolkit-2404 snap.
version: 1.0.0

grade: devel
confinement: strict

platforms:
  # only for architecture of host
  arm64:
  amd64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

package-repositories:
  - type: apt
    ppa: kobuk-team/intel-graphics
    key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    target: $SNAP/openvino

apps:
  validate-openvino:
    command-chain: ["command-chain/openvino-launch"]
    command: /usr/bin/python3 $SNAP/validate_openvino.py
    plugs:
      - opengl # Intel GPU access (device nodes)
      - intel-npu # Intel NPU access (device node)
      - npu-libs # Intel NPU access (libs)
      - openvino-libs # OpenVINO runtime
    environment:
      LD_LIBRARY_PATH: $SNAP/npu-libs:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

parts:
  validate-openvino:
    source: src/
    plugin: dump
    stage:
      - validate_openvino.py

  intel-graphics:
    plugin: nil
    stage-packages:
      - libigc-dev
      - libigc-tools
      - libigc2
      - libigdfcl-dev
      - libigdfcl2
      - intel-ocloc
      - intel-ocloc-dev
      - intel-opencl-icd
      - libze1
      - libze-dev
      - libze-intel-gpu-dev
      - libze-intel-gpu1
      - libigdgmm12
      - libigdgmm-dev

  command-chain-openvino:
    plugin: dump
    source-type: git
    source: https://github.com/canonical/openvino-toolkit-snap.git
    source-tag: 2025.2.0-amd64-rev30
    stage:
      - command-chain/openvino-launch

lint:
  ignore:
    - library:
      # These are needed but are flagged
      # by the linter because they are not
      # explicitly linked to any binary or
      # shared object
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbbind*
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbmalloc*
      - openvino/usr/runtime/3rdparty/tbb/lib/libhwloc*
      - usr/lib/x86_64-linux-gnu/libva.so.*
      - usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.*
      - usr/local/lib/libiga64.so*
      - usr/local/lib/libigc.so.*
      - usr/local/lib/libigdfcl.so.*
      - usr/local/lib/libopencl-clang*
