name: openvino-sample-consumer
base: core24
summary: Sample OpenVINO content consumer for testing and validation
description: |
  This snap is used for validating the openvino-toolkit-2404 snap.
version: 1.0.0

grade: devel
confinement: strict

platforms:
  # only for architecture of host
  arm64:
  amd64:

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    target: $SNAP/openvino

apps:
  validate-openvino:
    command-chain: ["command-chain/openvino-launch"]
    command: usr/bin/python3 $SNAP/validate_openvino.py
    plugs:
      - opengl # Intel GPU access (device nodes)
      - intel-npu # Intel NPU access (device node)
      - npu-libs # Intel NPU access (libs)
      - openvino-libs # OpenVINO runtime
    environment:
      # Intel OpenCL libs install to /usr/local/lib
      LD_LIBRARY_PATH: $SNAP/npu-libs:$SNAP/usr/local/lib:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

parts:
  validate-openvino:
    source: src/
    plugin: dump
    stage:
      - validate_openvino.py

  python-deps:
    source: src/
    plugin: python
    python-packages: 
      - pytest
      - numpy>=1.16.6,<2.3.0 # openvino dep
      - openvino-telemetry>=2023.2.1 # openvino dep
      - packaging # openvino dep
    stage-packages:
      - python3-minimal # python interpreter
      - python3.12-minimal # python interpreter
      - libva2 # openvino gpu plugin dep
      - libgl1 # opencv-python dep
      - libglu1-mesa # opencv-python dep
      - libxcb1 # opencv-python dep
      - libice6 # opencv-python dep
      - libsm6 # opencv-python dep
      - libx11-6 # opencv-python dep
      - libxext6 # opencv-python dep
    stage:
      - -usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libicuio.so.74.2
      - -usr/lib/x86_64-linux-gnu/libicutest.so.74.2
      - -usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275
      - -usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
      - -usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicutu.so.74.2
      - -usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
      - -usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicui18n.so.74.2

  opencl-driver:
    # Includes all the compute runtime and OpenCL bits needed for Intel GPU support
    plugin: nil
    build-packages:
      - wget
    override-build: |
      mkdir -p neo
      cd neo
      # Install Intel graphics compiler and compute runtime
      # This is required to enable GPU support for OpenVINO
      # https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html
      wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-core-2_2.5.6+18417_amd64.deb
      wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-opencl-2_2.5.6+18417_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-level-zero-gpu_1.6.32224.5_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-opencl-icd_24.52.32224.5_amd64.deb
      wget https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/libigdgmm12_22.5.5_amd64.deb
      dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
      # update paths to the Intel Installable Client Drivers (ICDs) for OpenCL
      intel_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel.icd
      intel_icd_so_path=$(cat ${intel_icd})
      base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current"
      echo "${base_path}""${intel_icd_so_path}" > "${intel_icd}"
      intel_legacy1_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel_legacy1.icd
      if [ -f ${intel_legacy1_icd} ]; then
        intel_legacy1_icd_so_path=$(cat ${intel_legacy1_icd})
        echo "${base_path}""${intel_legacy1_icd_so_path}" > "${intel_legacy1_icd}"
      fi
      # fix broken sym links
      cd "${CRAFT_PART_INSTALL}"
      ln -sf "${base_path}"/usr/bin/ocloc-24.39.1 etc/alternatives/ocloc
      ln -sf "${base_path}"/etc/alternatives/ocloc usr/bin/ocloc
      craftctl default

  command-chain-openvino:
    plugin: dump
    source-type: git
    source: https://github.com/canonical/openvino-toolkit-snap.git
    source-tag: 2024.6.0-0
    stage:
      - command-chain/openvino-launch

lint:
  ignore:
    - library:
      # These are needed but are flagged
      # by the linter because they are not
      # explicitly linked to any binary or
      # shared object
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbbind*
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbmalloc*
      - openvino/usr/runtime/3rdparty/tbb/lib/libhwloc*
      - usr/lib/x86_64-linux-gnu/libva.so.*
      - usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.*
      - usr/local/lib/libiga64.so*
      - usr/local/lib/libigc.so.*
      - usr/local/lib/libigdfcl.so.*
      - usr/local/lib/libopencl-clang*
