#!/bin/bash
#
# This script is designed to set up the runtime
# environment for applications consuming the OpenVINO
# content producer snap. It also checks for user access
# to device nodes required for using the GPU and NPU plugins
# and emits a warning if a node is inaccessible.
#

CONTENT_PATH="${SNAP}/openvino"
if [ ! -d "${CONTENT_PATH}" ]; then
  echo "Warning: ${CONTENT_PATH} not present inside ${SNAP_NAME} snap. Please connect the content interface at this path."
fi
export LD_LIBRARY_PATH="${SNAP}/openvino/usr/lib/$(uname -m)-linux-gnu":$LD_LIBRARY_PATH
export PYTHONPATH="${SNAP}/openvino/usr/lib/python3/dist-packages":$PYTHONPATH

# Check if device node is an Intel GPU
node_is_intel_gpu() {
  node=$1
  render_device_name=$(echo "{$node}" | cut -f4 -d"/") # e.g. renderD128
  gpu_info=$(intel_gpu_top -L | grep -B1 -w "${render_device_name}")
  if echo "${gpu_info}" | grep -qw "pci:vendor=8086"; then
    return 0 # this node is an Intel GPU
  fi
  return 1 # not an Intel GPU
}

# Check user access to Intel accelerator devices (GPU and NPU)
check_user_access() {
  node=$1
  if echo "${node}" | grep -q render; then
    if ! node_is_intel_gpu "${node}"; then
      return 0 # non-Intel GPUs unsupported
    fi
    device_type="GPU"
  else
    device_type="NPU"
  fi

  if ! test -r "${node}" || ! test -w "${node}"; then
    echo "Warning: to use device ${node} with the ${device_type} plugin, the user must have read and write access to ${node}."
    echo "Please run 'sudo chown root:render ${node} && sudo chmod g+rw ${node}'."
    echo "Also confirm (run 'snap connections') that snap interfaces required to access ${node} are connected."
  fi

  if ! id -nGz "${USER}" | grep -qzxF render; then
    echo "Warning: to use the ${device_type} plugin, the user must be in the render group."
    echo "Please run 'sudo usermod -a -G render ${USER}' then log out and back in."
  fi
}

for node in /dev/dri/render*; do
  [[ -e "${node}" ]] || break
  check_user_access "${node}"
done
for node in /dev/accel/accel*; do
  [[ -e "${node}" ]] || break
  check_user_access "${node}"
done

exec "$@"
