name: openvino-toolkit-2404
base: core24
summary: Intel's OpenVINO Toolkit
description: |
  OpenVINO™ is an open-source toolkit for optimizing and deploying AI inference.
  This snap also includes the OpenVINO GenAI extensions. For more information, visit https://openvino.ai

  For Intel NPU support, make sure to also install the intel-npu-driver snap:

  sudo snap install intel-npu-driver

grade: stable
confinement: strict
adopt-info: openvino

website: https://openvino.ai
contact: https://github.com/canonical/openvino-toolkit-snap/issues
issues: https://github.com/canonical/openvino-toolkit-snap/issues
source-code: https://github.com/openvinotoolkit/openvino
license: Apache-2.0

platforms:
  arm64:
  amd64:

# the recommended mountpoint for the content is /openvino
slots:
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    read:
      - /

parts:

  openvino:
    source-type: git
    source: https://github.com/openvinotoolkit/openvino.git
    source-tag: 2026.2.1
    plugin: cmake
    cmake-parameters:
      - -DENABLE_PYTHON=ON
      - -DPython3_EXECUTABLE=/usr/bin/python3.12
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_SYSTEM_TBB=ON
      - -DENABLE_SYSTEM_SNAPPY=ON
      - -DENABLE_SNAPPY_COMPRESSION=ON
      - -DCPACK_GENERATOR=DEB
      - -DENABLE_SAMPLES=OFF
      - -DENABLE_PYTHON_PACKAGING=ON
      - -DOPENVINO_EXTRA_MODULES=./openvino.genai
      - -DCPACK_ARCHIVE_COMPONENT_INSTALL=OFF
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | tr -d 'v')"
      git submodule update --init --recursive
      git clone -b 2026.2.1.0 --recursive https://github.com/openvinotoolkit/openvino.genai.git
      # apply pybind11 fix to openvino.genai
      # https://github.com/openvinotoolkit/openvino.genai/pull/3915
      cd openvino.genai
      git remote add frenchwr https://github.com/frenchwr/openvino.genai.git
      git fetch frenchwr frenchwr/pybind11-fix
      git cherry-pick b67a24ed9a2ca0960925b4b3507d0b2eabaa0357
      cd ..
    override-build: |
      # openvino build requires recent version of setuptools
      pip install --upgrade setuptools --break-system-packages
      craftctl default
    build-packages:
      - ca-certificates
      - file
      - build-essential
      - ninja-build
      - scons
      - ccache
      - pkgconf
      - git
      - shellcheck
      - patchelf
      - fdupes
      - gzip
      - lintian
      - libtbb-dev
      - libpugixml-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - rapidjson-dev
      - libva-dev
      - libsnappy-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - libpython3-dev
      - pybind11-dev
      - libffi-dev
      - python3-enchant
      - wget
      - libsnappy-dev
    stage-packages:
      - ocl-icd-libopencl1
      - libtbb12
      - libsnappy1v5
      - to amd64:
        - intel-gpu-tools
    organize:
      usr/runtime/lib/intel64/libopenvino_tokenizers.so: usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libopenvino_tokenizers.so
      usr/runtime/lib/intel64/libopenvino_genai.*: usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/
      usr/python/openvino_genai: usr/lib/python3/dist-packages/openvino_genai

  openvino-deps:
    source: .
    plugin: python
    python-packages:
      - numpy==2.2.6
      - packaging==25.0
    organize:
      lib/python3.12/site-packages/numpy: usr/lib/python3/dist-packages/numpy
      lib/python3.12/site-packages/numpy.libs: usr/lib/python3/dist-packages/numpy.libs
      lib/python3.12/site-packages/packaging: usr/lib/python3/dist-packages/packaging

  openvino-tokenizers:
    # build openvino_tokenizers from source to ensure binary compatability with openvino
    after: [openvino]
    source-type: git
    source: https://github.com/openvinotoolkit/openvino_tokenizers
    source-tag: 2026.2.1.0
    plugin: nil
    build-packages:
    - libtbb-dev
    build-environment:
      - OpenVINO_DIR: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
    override-build: |
      # note, extra-index-url is needed for build dependencies only
      pip install --break-system-packages --no-deps . --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
      cp -r $CRAFT_PART_BUILD/python $CRAFT_PART_INSTALL
    organize:
      python/openvino_tokenizers: usr/lib/python3/dist-packages/openvino_tokenizers

  command-chain:
    plugin: dump
    source: command-chain/
    organize:
      openvino-launch: command-chain/openvino-launch

lint:
  ignore:
    - library:
      # OpenVINO libs consumed by other snaps
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libopenvino*
      # Linked by libopenvino_tensorflow_frontend
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsnappy*
      # Not explicitly linked but dlopen'd
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libtbbbind*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libtbbmalloc*
      # Linked by libtbbbind
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libhwloc*
