name: openvino-toolkit-2404
base: core24
summary: Intel's OpenVINO Toolkit
description: |
  OpenVINO™ is an open-source toolkit for optimizing and deploying AI inference.

grade: devel
confinement: strict
adopt-info: openvino

platforms:
  arm64:
  amd64:

# the recommended mountpoint for the content is /openvino
slots:
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    read:
      - /

parts:
  openvino:
    source-type: git
    source: https://github.com/openvinotoolkit/openvino.git
    source-tag: 2024.6.0
    plugin: cmake
    cmake-parameters:
      - -DENABLE_PYTHON=ON
      - -DPython3_EXECUTABLE=/usr/bin/python3.12
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_SYSTEM_TBB=ON
      - -DENABLE_SYSTEM_SNAPPY=ON
      - -DENABLE_SNAPPY_COMPRESSION=ON
      - -DCPACK_GENERATOR=DEB
      - -DENABLE_SAMPLES=OFF
      - -DENABLE_PYTHON_PACKAGING=ON
    override-pull: |
      craftctl default
      git submodule update --init --recursive
      craftctl set version="$(git describe --tags)"
    override-build: |
      craftctl default
      rm -rf ${CRAFT_PART_INSTALL}/usr/{share,include,bin}
    build-packages:
      - ca-certificates
      - file
      - build-essential
      - ninja-build
      - scons
      - ccache
      - pkgconf
      - git
      - shellcheck
      - patchelf
      - fdupes
      - gzip
      - lintian
      - libtbb-dev
      - libpugixml-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - rapidjson-dev
      - libva-dev
      - libsnappy-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - libpython3-dev
      - pybind11-dev
      - libffi-dev
      - python3-enchant
      - wget
      - libsnappy-dev
    stage-packages:
      - ocl-icd-libopencl1
      - libtbb12
      - libsnappy1v5

lint:
  ignore:
    - library:
      # OpenVINO libs consumed by other snaps
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libopenvino*
      # Linked by libopenvino_tensorflow_frontend
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libsnappy*
      # Not explicitly linked but dlopen'd
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libtbbbind*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libtbbmalloc*
      # Linked by libtbbbind
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libhwloc*