name: openvino-toolkit-2404
base: core24
version: '2024.4.0'
summary: Intel's OpenVINO Toolkit
description: |
  OpenVINO™ is an open-source toolkit for optimizing and deploying AI inference.

grade: devel
confinement: strict
adopt-info: openvino

platforms:
  amd64:

# the recommended mountpoint for the content is /openvino
slots:
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    read:
      - /

parts:
  openvino:
    source-type: git
    source: https://github.com/openvinotoolkit/openvino.git
    source-tag: 2024.4.0
    plugin: cmake
    cmake-parameters:
      - -DENABLE_PYTHON=ON
      - -DPython3_EXECUTABLE=/usr/bin/python3.12
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-pull: |
      craftctl default
      git submodule update --init --recursive
    stage:
      - -usr/runtime/3rdparty/tbb/lib/libtbbbind*
      - -usr/runtime/3rdparty/tbb/lib/libtbbmalloc*
      - -usr/runtime/3rdparty/tbb/lib/libhwloc.so.15.6.4
    build-packages:
      - ca-certificates
      - file
      - build-essential
      - ninja-build
      - scons
      - ccache
      - gcc-multilib
      - g++-multilib
      - pkgconf
      - git
      - shellcheck
      - patchelf
      - fdupes
      - gzip
      - lintian
      - libtbb-dev
      - libpugixml-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - rapidjson-dev
      - libva-dev
      - libsnappy-dev
      - python3-pip
      - python3-venv
      - python3-setuptools
      - libpython3-dev
      - pybind11-dev
      - libffi-dev
      - python3-enchant
      - wget
    stage-packages:
      - ocl-icd-libopencl1
