job_queue: REPLACE_QUEUE
output_timeout: 7200
provision_data:
  url: REPLACE_IMAGE_URL
test_data:
  attachments:
    - local: REPLACE_ATTACHMENT_1
      agent: "checkbox-openvino-toolkit-2404.snap"
    - local: REPLACE_ATTACHMENT_2
      agent: "sample-consumer.snap"
    - local: ".github/testflinger/set-device-access.sh"
      agent: "set-device-access.sh"
  test_cmds: |

    set -e

    # retrieve the tools installer
    curl -Ls -o install_tools.sh https://raw.githubusercontent.com/canonical/hwcert-jenkins-tools/main/install_tools.sh
    # install the scriptlets and other tools on the agent and the device, as necessary
    export TOOLS_PATH=tools
    source install_tools.sh $TOOLS_PATH

    # ensure device is available before continuing
    wait_for_ssh --allow-degraded

    echo
    echo "====== TARGET DEVICE CONNECTION INFO ======"
    echo
    echo DEVICE_IP: ubuntu@$DEVICE_IP
    echo
    echo "==========================================="
    echo

    # Avoid GPG errors on old unsupported versions of Chrome, which we don't test anyway
    _run sudo rm -f /etc/apt/sources.list.d/google-chrome.list

    _run sudo snap refresh
    _run sudo snap install openvino-toolkit-2404 --channel latest/edge

    _put attachments/test/sample-consumer.snap :/home/ubuntu/sample-consumer.snap
    _run sudo snap install --dangerous /home/ubuntu/sample-consumer.snap
    _run sudo snap install checkbox24
    _put attachments/test/checkbox-openvino-toolkit-2404.snap :/home/ubuntu/checkbox-openvino-toolkit-2404.snap
    _run sudo snap install --dangerous --classic /home/ubuntu/checkbox-openvino-toolkit-2404.snap

    _put attachments/test/set-device-access.sh :/home/ubuntu/set-device-access.sh

    # Run the validation twice:
    #
    # Run 1: original debs and kernel from the certified image
    # Run 2: upgraded debs and kernel, following a reboot
    #
    _run sudo bash set-device-access.sh
    _run checkbox-openvino-toolkit-2404.test-runner-automated

    _run sudo apt update
    _run sudo apt -y upgrade
    _run sudo reboot
    wait_for_ssh --allow-degraded

    _run checkbox-openvino-toolkit-2404.test-runner-automated
