name: Pull Request

on:
  pull_request:
    paths:
      - 'snap/**'
      - 'command-chain/**'
      - '.github/workflows/smoke-tests.yaml'
    branches:
      - openvino-toolkit-2404
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build snap, run smoke tests, release to edge
    runs-on: [self-hosted, linux, X64, xlarge, jammy]
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
      - name: Find and parse snapcraft.yaml
        id: snapcraft-yaml
        uses: snapcrafters/ci/parse-snapcraft-yaml@main
      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: ${{ steps.snapcraft-yaml.outputs.project-root }}
      - name: Review the built snap
        uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: ${{ steps.snapcraft-yaml.outputs.classic }}
          plugs: ${{ steps.snapcraft-yaml.outputs.plugs-file }}
          slots: ${{ steps.snapcraft-yaml.outputs.slots-file }}
      - name: Install the snap
        shell: bash
        run: |
          sudo snap install --dangerous "${{ steps.build.outputs.snap }}"
      - name: Release to latest/edge
        id: publish
        shell: bash
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_PE_BOT }}
          SNAP_FILE: ${{ steps.build.outputs.snap }}
        run: |
          snapcraft push "$SNAP_FILE" --release=latest/edge